export const LOAD_POST_START = " LOAD_POST_START"
export const LOAD_POST_SUCCESS = "  LOAD_POST_SUCCESS"
export const LOAD_POST_ERROR = " LOAD_POST_ERROR"


export const UPDATE_POST_START = "UPDATE_POST_START"
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR"